#!/bin/bash

CATEGORIES=$'
conferences,
family,
gadgets,
howto,
photo,
posts (fallback),
projects,
reactions,
reading,
study,
thoughts,
trips'

TAGS=$'backups,
books,
communication,
conference,
covid-19,
desktop,
dev,
digimarks,
energy,
ethics,
europython,
family,
fosdem,
gadgets,
health,
hosting,
howto,
journal,
kids,
life,
link,
linux,
meta,
mobile,
music,
networking,
notifications,
opensource,
photography,
python,
rant (fallback),
secondbrain,
space,
sync,
tech,
trip,
ubuntu,
vim,
web,
work'

DAMMITDIR=$( dirname "$(readlink -f $0)" )
ACTION=$1

if [ -z "$ACTION" ]; then
    ACTION="unknown"
fi

if [ $ACTION == "update" ]; then
    echo "Please use the webhook"
elif [ $ACTION == "drafts" ]; then
    cd ${DAMMITDIR}/content/posts
    grep -r "Status:" . | grep -i draft | cut -d. -f2 | cut -c 2- | sort
elif [ "$ACTION" == 'new' ] && [ -z "$2" ]; then
    echo "[!] Please provide a slug (e.g., new-post-subject)"
    exit
elif [ $ACTION == "new" ]; then
    SLUG=$2
    BLOGPOSTFILE="${DAMMITDIR}/content/posts/${SLUG}.md"
    if [ -e ${BLOGPOSTFILE} ]; then
        echo "[!] A blogpost with this slug already exists!"
        exit
    fi

    cd ${DAMMITDIR}
    echo "Creating new blogpost with slug ${SLUG} in ${BLOGPOSTFILE}"

    STARTED=$( date +'%Y-%m-%d %H:%M:%S' )
    echo "Title: " >> ${BLOGPOSTFILE}
    echo "Started: ${STARTED}" >> ${BLOGPOSTFILE}
    echo "Date: ${STARTED}" >> ${BLOGPOSTFILE}
    echo "Slug: ${SLUG}" >> ${BLOGPOSTFILE}
    echo "Location: " >> ${BLOGPOSTFILE}
    echo "Authors: Michiel Scholten" >> ${BLOGPOSTFILE}
    echo "Category: " >> ${BLOGPOSTFILE}
    echo ${CATEGORIES} >> ${BLOGPOSTFILE}
    echo "Tags: " >> ${BLOGPOSTFILE}
    echo ${TAGS} >> ${BLOGPOSTFILE}
    echo "Image: " >> ${BLOGPOSTFILE}
    echo "Status: draft" >> ${BLOGPOSTFILE}
    echo "" >> ${BLOGPOSTFILE}
    vim ${BLOGPOSTFILE}

    read -p "Do you want to add it to version control now and commit? (y|N) " -n 1 -r
    echo  # Ensure line break after answer
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        cd ${DAMMITDIR}/content/posts
        git add "${BLOGPOSTFILE}"
        git commit "${BLOGPOSTFILE}"
    else
        echo "Do not forget to add it to version control later!"
    fi

elif [ $ACTION == "edit" ]; then
    SLUG=$2
    BLOGPOSTFILE="${DAMMITDIR}/content/posts/${SLUG}.md"
    if [ ! -f ${BLOGPOSTFILE} ]; then
        echo "[!] Blogpost ${BLOGPOSTFILE} not found"
        exit
    fi

    cd ${DAMMITDIR}
    vim ${BLOGPOSTFILE}
    git commit ${BLOGPOSTFILE}
else
    echo "[!] Provide an ACTION to perform"
    echo "    Choose from:"
    echo "    - new <slug>       Create a new post with filename <slug>"
    echo "    - edit <slug>      Continue editing <slug>, git commit after"
    echo "    - drafts           List all posts currently in draft"
    #echo "    - update           Generate update and upload to server"
    exit
fi
